### ISSUE TITLE
Is this project alive and stable?

### ISSUE THREAD

**Issue by asyncee** [Finistere/antidote#1]
Hello! Thanks for this library, but i see that there is no project activity, no new commits, issues, etc.

Is this project still alive and are there any plans to improve (i saw todo list in readme)?

Also, do you use antidote in production?

**Comment by Finistere** [comment]
Hello. :) It isn't dead ! I still have the intention to improve it. ;) However, I have to admit that I haven't worked on it for some time... So thanks for the issue, glad to see someone cares enough to ask !

I've used it in a (relatively small) project in production, and it was quite pleasant to work with. The core of antidote, typically ìnject()`, `factory()` and `register()`, can be considered stable. I don't expect them to change anytime soon. And the project has 100 % test coverage and everything is documented. So while it would be dishonest to say it's battle-tested and 100% production-ready, it's far from being an beta version.

But there are things I'm not satisfied with. In particular how configuration is defined. I've recently played a bit with Pyramid, and I'm quite fond of how they manage configuration. In short, I currently don't intend to add major features or break everything, but wish to improve its usability. It still has some rough edges.

If you have any feature request or found any bug, don't hesitate to create an issue, I will respond in a timely manner and do my best to enhance antidote ! ;)

**Comment by asyncee** [comment]
Great to read such a detailed answer, thanks! I wish you success!

**Comment by pauleveritt** [comment]
Sorry for replying to a closed issue.

I'm an old Pyramid/Zope guy that has been working for a couple of years on a registry and injection system, built for a particular use (component driven development.) It has a lot of overlap with what you're doing.

If you're still interested in antidote and interested in co-maintainer, I could try to describe things I might need to bring over and see if you're interested in those additions. (And if not, if the core could support it as an extension or something.)

**Comment by Finistere** [comment]
Hello!

I'm still maintaining Antidote, even though I'm not actively working on it. Taking the time to create Python 3.10 wheels just now. :) At the very least, I'm interested in talking! What would like to add or change (roughly)? 

> component driven development

What are you referring to? From a quick look I have only seen references to UI development.

> if the core could support it as an extension or something

Unless you intend to do some radical changes, it would be implemented as an extension to core, like almost everything from the public API: `@service`, `@factory` ... `antidote.core` could be summarized as a hash map with logic for thread-safety, proper lazy dependency instantiation, and function injection. That's it. Its only, although big, limitation I'm aware of is the lack of async support for dependency instantiation.

Could you please open a new issue for further discussion?

**Comment by pauleveritt** [comment]
I finally (but quietly) published what I've been working on. Here's [component driven development](https://viewdom.readthedocs.io/en/latest/examples/hopscotch.html) where a component is looked up in a registry and injection is used to create it. Here's the [docs for the registry](https://hopscotch.readthedocs.io/en/latest/)

I still need to rewrite the next 3 layers atop this before I'll say anything in public. And I very much need to see what would be missing if I moved ViewDOM to antidote, and create individual tickets along the way.

**Comment by Finistere** [comment]
From a quick look on Hopscotch:

1.  `@injectable()` is equivalent to `@service()`
https://antidote.readthedocs.io/en/stable/reference.html#module-antidote.service

2. `@injectable(kind=...)` and `@injectable(kind=..., context=...)` are close to `@implementation()` and     `@implementation(permanent=False)` respectively. I did something similar to `kind` in an earlier version of Antidote. However, I removed it because:
   
   - It's complex to track what exists or not, you need to search all subclasses / do a grep. Neither are optimal.
   - You can't guarantee easily that implementations will be imported before you actually need them.
   
   With `@implementation` by design requires you to import everything needed before, and you can just do a "go to definition" in  
any IDE to dig down the dependency path.

   https://antidote.readthedocs.io/en/stable/reference.html#module-antidote.implementation

3. For `get()` / `context()` I didn't check the actual implementation, but I see no reason for it to be a problem in Antidote. `Constants` & `const()` have a similar API. Internally `const()` creates a placeholder that will be replaced by a descriptor by the metaclass `Constants`, would could be also just be a simple class decorator.
https://antidote.readthedocs.io/en/stable/reference.html#constants

For the point 2), it shouldn't be difficult to add this logic to Antidote if you need it with a custom `Provider`:
https://antidote.readthedocs.io/en/stable/reference.html#module-antidote.core.provider

Feel free to use emails instead of this issue if you want to keep a low profile. My e-mail is available on any of the commits if you clone this project. ;)
